### ISSUE TITLE
Autoload explanation

### ISSUE THREAD

**Issue by SeaDude** [filsinger/emacs-config#1]
Hey there, 

I appreciate your blog post on using Git as an emacs init sync. Can you explain a bit how your `autoload` setup works? I use many emacs packages from Melpa rather than from github. Would be nice to understand what you are doing a bit better. 

Thanks

**Comment by filsinger** [comment]
Hey,

I cant believe I didn't see your issue until now, sorry for the delayed (better late than never I guess).  I wrote that blog before the package manager was part of Emacs.

My back in 2011 I was leveraging submodules to try make the plugins I was using easier to update and manage.  Leveraging `autoload` was a way to speed up my Emacs boot time.  In a basic sense, autoload provides a way to make emacs aware of functions that are available in packages but will defer the actual loading of the whole package file until the first time a function in that package is called.  This helps speed up the initial Emacs boot time at the cost of taking a little more time the first time a module is actually needed.

The function [jf-generate-autoload-files](https://github.com/filsinger/emacs-config/blob/907e66c831a49f2b6cbde0b7f20ac785e59d816c/custom/jf-generate-autoload.el#L5-L21) parses everything in the `custom` and `submodules` folder, it looks for any function with the `;;;###autoload` comment before it (this is done by `update-directory-autoloads` in `autoload.el` which is part of emacs). `(autoload ...)` calls are automatically added to [autoload/my-super-autoload.el](https://github.com/filsinger/emacs-config/blob/907e66c831a49f2b6cbde0b7f20ac785e59d816c/autoload/my-super-autoload.el) for every `;;;###autoload` marked function in those directories.  After the `autoload/my-super-autoload.el` file is finished generating it is byte compiled.

My [common-init.el](https://github.com/filsinger/emacs-config/blob/907e66c831a49f2b6cbde0b7f20ac785e59d816c/common-init.el#L161-L164) has a block of code that will attempt to load the `autoload/my-super-autoload.el` if it exists, if not it will load the `jf-generate-autoload,el` so that the `jf-generate-autoload` function is available (which is needed by the `generate-autoloads.sh` script)

```elisp
(if (file-readable-p (concat emacs-autoloads-path "my-super-autoload.el"))
    (require 'my-super-autoload)
  (require 'jf-generate-autoload) ;; need to load the jf-generate-autoload if we dont have the super autoload file when we are doing an initial creation of the super autoload file.
)
```

I've mostly moved away from using submodules as a way to manage plugins, the package manager is a FAR better solution.

`autoload` is still a useful feature for speeding up Emacs boot times if you have a lost of custom functions. You can find out more about it here: https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html
